language: android

# Use the Travis Container-Based Infrastructure
sudo: false

jdk:
  - oraclejdk8

env:
  global:
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2
    - ADB_INSTALL_TIMEOUT=20 # install timeout in minutes (2 minutes by default)
  matrix:
    - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install new Android SDK tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - $ANDROID_TARGET
    - android-25

    # Support library
    #- extra-android-support
    #- extra-android-m2repository

    # System images
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

before_script:
  - chmod +x ./gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  # Emulator Management: Create, Start and Wait
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &

script:
  - ./gradlew build && android-wait-for-emulator
  - ./gradlew connectedCheck
  
notifications:
  email:
    - kyle.white@wearehathway.com
